resources(
    sources = [
        "*.xml",
        "*.yml",
        "com/twitter/slo/slo.json",
        "config/*.yml",
        "config/auth/policykeeper/**/*.yaml",
    ],
)

files(
    name = "config_files",
    sources = ["config/**/*"],
)
