scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/fasterxml/jackson/dataformat:jackson-dataformat-yaml",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/exceptions",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/logger",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/storage",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/storage/common",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/storage/configbus/parser",
        "auth/policykeeper/thrift/src/main/thrift:thrift-scala",
        "configbus/subscriber",
    ],
)
