scala_library(
    name = "javahelpers",
    sources = ["**/*.scala"],
    platform = "java8",
    provides = artifact(
        org = "com.twitter",
        name = "auth-pasetoheaders-javahelpers",
        repo = artifactory,
    ),
    tags = ["bazel-compatible"],
    dependencies = [
    ],
)
