scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "servo/util/src/main/scala",
        "stitch/stitch-core",
        "util/util-stats",
    ],
)
