scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finatra-internal/api11/src/main/scala/com/twitter/finatra/api11:errors",
    ],
)
