scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/dataproviders",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/dataproviders/implementations/auth",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/dataproviders/implementations/input",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/dataproviders/implementations/unittests",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/evaluationengine",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/exceptions",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/interpolation",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/logger",
        "auth/policykeeper/thrift/src/main/thrift:thrift-scala",
        "servo/util",
    ],
)
