scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/github/nscala_time",
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/net/codingwell:scala-guice",
        "flightauth/thrift/src/main/thrift:thrift-scala",
        "strato/src/main/scala/com/twitter/strato/client",
        "strato/src/main/scala/com/twitter/strato/thrift",
    ],
)
