scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "auth/sso/src/main/thrift/com/twitter/auth/sso:auth-sso-scala",
    ],
)
