scala_library(
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/net/codingwell:scala-guice",
        "account_security/tsla/src/main/thrift/com/twitter/tsla/auth_events:auth-event-scala",
        "finagle/finagle-core/src/main",
        "passbird/thrift-only/src/main/thrift:thrift-scala",
        "twitter-server/server/src/main/scala",
    ],
)
