python37_binary(
    name = "hnsw-query-server-cli",
    source = "hnsw-query-server-cli.py",
    tags = [
        "bazel-compatible:migrated",
    ],
    dependencies = [
        "ann/src/main/aurora/service/query_server/hnsw:aurora-file",
    ],
)

python37_binary(
    name = "faiss-query-server-cli",
    source = "faiss-query-server-cli.py",
    tags = [
        "bazel-compatible:migrated",
    ],
    dependencies = [
        "ann/src/main/aurora/service/query_server/faiss:aurora-file",
    ],
)
