jvm_binary(
    name = "bin",
    basename = "screech-owl-listener",
    main = "com.twitter.screechowl.listener.ScreechOwlListener",
    runtime_platform = "java11",
    dependencies = [
        "src/scala/com/twitter/screechowl/listener",
    ],
)
