target(
    dependencies = [
        "auth/sso/src/main/scala/com/twitter/auth/sso/client",
        "auth/sso/src/main/scala/com/twitter/auth/sso/models",
        "auth/sso/src/main/scala/com/twitter/auth/sso/service",
        "auth/sso/src/main/scala/com/twitter/auth/sso/store",
    ],
)
