jvm_app(
    name = "screech-owl-alerter",
    binary = "src/scala/com/twitter/screechowl/alerter:bin",
)

jvm_app(
    name = "screech-owl-listener",
    binary = "src/scala/com/twitter/screechowl/listener:bin",
)
