scala_library(
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/net/codingwell:scala-guice",
        "account_security/tsla/src/main/scala/com/twitter/tsla/util/auth_events",
        "auth/pasetoheaders/src/main/scala/com/twitter/auth/pasetoheaders/thriftconversion",
        "auth/passport-tools/src/main/scala/com/twitter/auth/passport_tools",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/context",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/exceptions",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/logger",
        "auth/policykeeper/thrift/src/main/thrift:thrift-scala",
        "finagle/finagle-core/src/main",
        "finatra-internal/authentication/src/main/scala",
    ],
)
