scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/dataproviderservice",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/evaluationengine",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/evaluationengine/scalastaticengine",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/evaluationservice",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/exceptions",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/logger",
        "auth/policykeeper/server/src/main/scala/com/twitter/auth/policykeeper/api/services",
        "auth/policykeeper/thrift/src/main/thrift:thrift-scala",
        "decider",
    ],
)
